'use strict';

import * as vscode from 'vscode';

export class Suggestion {
    keyword: string;
    detail: string;
    documentation: string;
    constructor(_keyword: string, _detail: string, _documentation: string) {
        this.keyword = _keyword;
        this.detail = _detail;
        this.documentation = _documentation
    }
}

export const rhetosSuggestions : Suggestion[] = [
    new Suggestion('Action', 'Action detail', 'Action documentation'),
    new Suggestion('AktualniKorisnik', 'AktualniKorisnik detail', 'AktualniKorisnik documentation'),
    new Suggestion('Allow', 'Allow detail', 'Allow documentation'),
    new Suggestion('AllowedRelationsTransitive', 'AllowedRelationsTransitive detail', 'AllowedRelationsTransitive documentation'),
    new Suggestion('AllowRead', 'AllowRead detail', 'AllowRead documentation'),
    new Suggestion('AllowWrite', 'AllowWrite detail', 'AllowWrite documentation'),
    new Suggestion('AllProperties', 'AllProperties detail', 'AllProperties documentation'),
    new Suggestion('AllPropertiesFrom', 'AllPropertiesFrom detail', 'AllPropertiesFrom documentation'),
    new Suggestion('AllPropertiesWithCascadeDeleteFrom', 'AllPropertiesWithCascadeDeleteFrom detail', 'AllPropertiesWithCascadeDeleteFrom documentation'),
    new Suggestion('ApplyFilterOnClientRead', 'ApplyFilterOnClientRead detail', 'ApplyFilterOnClientRead documentation'),
    new Suggestion('ApplyOnClientRead', 'ApplyOnClientRead detail', 'ApplyOnClientRead documentation'),
    new Suggestion('AutoCode', 'AutoCode detail', 'AutoCode documentation'),
    new Suggestion('AutoCodeCached', 'AutoCodeCached detail', 'AutoCodeCached documentation'),
    new Suggestion('AutoCodeForEach', 'AutoCodeForEach detail', 'AutoCodeForEach documentation'),
    new Suggestion('AutodetectSqlDependencies', 'AutodetectSqlDependencies detail', 'AutodetectSqlDependencies documentation'),
    new Suggestion('AutoInheritRowPermissions', 'AutoInheritRowPermissions detail', 'AutoInheritRowPermissions documentation'),
    new Suggestion('BeforeAction', 'BeforeAction detail', 'BeforeAction documentation'),
    new Suggestion('BeforeQuery', 'BeforeQuery detail', 'BeforeQuery documentation'),
    new Suggestion('Binary', 'Binary detail', 'Binary documentation'),
    new Suggestion('Bool', 'Bool detail', 'Bool documentation'),
    new Suggestion('Browse', 'Browse detail', 'Browse documentation'),
    new Suggestion('Browseable', 'Browseable detail', 'Browseable documentation'),
    new Suggestion('CascadeDelete', 'CascadeDelete detail', 'CascadeDelete documentation'),
    new Suggestion('ChangesOnBaseItem', 'ChangesOnBaseItem detail', 'ChangesOnBaseItem documentation'),
    new Suggestion('ChangesOnChangedItems', 'ChangesOnChangedItems detail', 'ChangesOnChangedItems documentation'),
    new Suggestion('ChangesOnLinkedItems', 'ChangesOnLinkedItems detail', 'ChangesOnLinkedItems documentation'),
    new Suggestion('Clustered', 'Clustered detail', 'Clustered documentation'),
    new Suggestion('ComposableFilterBy', 'ComposableFilterBy detail', 'ComposableFilterBy documentation'),
    new Suggestion('ComposableFilterByReferenced', 'ComposableFilterByReferenced detail', 'ComposableFilterByReferenced documentation'),
    new Suggestion('Computed', 'Computed detail', 'Computed documentation'),
    new Suggestion('ComputedFrom', 'ComputedFrom detail', 'ComputedFrom documentation'),
    new Suggestion('ComputeForNewBaseItems', 'ComputeForNewBaseItems detail', 'ComputeForNewBaseItems documentation'),
    new Suggestion('ComputeForNewItems', 'ComputeForNewItems detail', 'ComputeForNewItems documentation'),
    new Suggestion('ConvertFormat', 'ConvertFormat detail', 'ConvertFormat documentation'),
    new Suggestion('CreationTime', 'CreationTime detail', 'CreationTime documentation'),
    new Suggestion('CustomClaim', 'CustomClaim detail', 'CustomClaim documentation'),
    new Suggestion('DataSource', 'DataSource detail', 'DataSource documentation'),
    new Suggestion('DataSources', 'DataSources detail', 'DataSources documentation'),
    new Suggestion('DataStructure', 'DataStructure detail', 'DataStructure documentation'),
    new Suggestion('Date', 'Date detail', 'Date documentation'),
    new Suggestion('DateRange', 'DateRange detail', 'DateRange documentation'),
    new Suggestion('DateTime', 'DateTime detail', 'DateTime documentation'),
    new Suggestion('DateTimeRange', 'DateTimeRange detail', 'DateTimeRange documentation'),
    new Suggestion('Deactivatable', 'Deactivatable detail', 'Deactivatable documentation'),
    new Suggestion('Decimal', 'Decimal detail', 'Decimal documentation'),
    new Suggestion('Default', 'Default detail', 'Default documentation'),
    new Suggestion('DefaultLoadFilter', 'DefaultLoadFilter detail', 'DefaultLoadFilter documentation'),
    new Suggestion('Deny', 'Deny detail', 'Deny documentation'),
    new Suggestion('DenyRead', 'DenyRead detail', 'DenyRead documentation'),
    new Suggestion('DenySave', 'DenySave detail', 'DenySave documentation'),
    new Suggestion('DenyUserEdit', 'DenyUserEdit detail', 'DenyUserEdit documentation'),
    new Suggestion('DenyWrite', 'DenyWrite detail', 'DenyWrite documentation'),
    new Suggestion('Derives', 'Derives detail', 'Derives documentation'),
    new Suggestion('Detail', 'Detail detail', 'Detail documentation'),
    new Suggestion('Email', 'Email detail', 'Email documentation'),
    new Suggestion('Entity', 'Entity detail', 'Entity documentation'),
    new Suggestion('ExtAction', 'ExtAction detail', 'ExtAction documentation'),
    new Suggestion('ExtComposableFilterBy', 'ExtComposableFilterBy detail', 'ExtComposableFilterBy documentation'),
    new Suggestion('ExtDenySave', 'ExtDenySave detail', 'ExtDenySave documentation'),
    new Suggestion('Extends', 'Extends detail', 'Extends documentation'),
    new Suggestion('ExtendTrigger', 'ExtendTrigger detail', 'ExtendTrigger documentation'),
    new Suggestion('Extension', 'Extension detail', 'Extension documentation'),
    new Suggestion('ExternalReference', 'ExternalReference detail', 'ExternalReference documentation'),
    new Suggestion('ExtFilterBy', 'ExtFilterBy detail', 'ExtFilterBy documentation'),
    new Suggestion('ExtInvalidData', 'ExtInvalidData detail', 'ExtInvalidData documentation'),
    new Suggestion('FilterBy', 'FilterBy detail', 'FilterBy documentation'),
    new Suggestion('FilterByBase', 'FilterByBase detail', 'FilterByBase documentation'),
    new Suggestion('FilterByLinkedItems', 'FilterByLinkedItems detail', 'FilterByLinkedItems documentation'),
    new Suggestion('FilterByReferenced', 'FilterByReferenced detail', 'FilterByReferenced documentation'),
    new Suggestion('From', 'From detail', 'From documentation'),
    new Suggestion('Guid', 'Guid detail', 'Guid documentation'),
    new Suggestion('Hierarchy', 'Hierarchy detail', 'Hierarchy documentation'),
    new Suggestion('History', 'History detail', 'History documentation'),
    new Suggestion('Implements', 'Implements detail', 'Implements documentation'),
    new Suggestion('InheritFrom', 'InheritFrom detail', 'InheritFrom documentation'),
    new Suggestion('InheritFromBase', 'InheritFromBase detail', 'InheritFromBase documentation'),
    new Suggestion('Integer', 'Integer detail', 'Integer documentation'),
    new Suggestion('IntegerRange', 'IntegerRange detail', 'IntegerRange documentation'),
    new Suggestion('InvalidData', 'InvalidData detail', 'InvalidData documentation'),
    new Suggestion('Is', 'Is detail', 'Is documentation'),
    new Suggestion('ItemFilter', 'ItemFilter detail', 'ItemFilter documentation'),
    new Suggestion('ItemFilterReferenced', 'ItemFilterReferenced detail', 'ItemFilterReferenced documentation'),
    new Suggestion('Jmbg', 'Jmbg detail', 'Jmbg documentation'),
    new Suggestion('KeepSynchronized', 'KeepSynchronized detail', 'KeepSynchronized documentation'),
    new Suggestion('KeyProperties', 'KeyProperties detail', 'KeyProperties documentation'),
    new Suggestion('KeyProperty', 'KeyProperty detail', 'KeyProperty documentation'),
    new Suggestion('KeyPropertyID', 'KeyPropertyID detail', 'KeyPropertyID documentation'),
    new Suggestion('LegacyEntity', 'LegacyEntity detail', 'LegacyEntity documentation'),
    new Suggestion('LegacyProperty', 'LegacyProperty detail', 'LegacyProperty documentation'),
    new Suggestion('LegacyPropertyReadOnly', 'LegacyPropertyReadOnly detail', 'LegacyPropertyReadOnly documentation'),
    new Suggestion('Length', 'Length detail', 'Length documentation'),
    new Suggestion('LimitAllowedRelationsTransitive', 'LimitAllowedRelationsTransitive detail', 'LimitAllowedRelationsTransitive documentation'),
    new Suggestion('LinkedItems', 'LinkedItems detail', 'LinkedItems documentation'),
    new Suggestion('LoadOldItems', 'LoadOldItems detail', 'LoadOldItems documentation'),
    new Suggestion('Lock', 'Lock detail', 'Lock documentation'),
    new Suggestion('LockExcept', 'LockExcept detail', 'LockExcept documentation'),
    new Suggestion('LockProperty', 'LockProperty detail', 'LockProperty documentation'),
    new Suggestion('Log', 'Log detail', 'Log documentation'),
    new Suggestion('Logging', 'Logging detail', 'Logging documentation'),
    new Suggestion('LongString', 'LongString detail', 'LongString documentation'),
    new Suggestion('LookupVisible', 'LookupVisible detail', 'LookupVisible documentation'),
    new Suggestion('Materialized', 'Materialized detail', 'Materialized documentation'),
    new Suggestion('MaxLength', 'MaxLength detail', 'MaxLength documentation'),
    new Suggestion('MaxValue', 'MaxValue detail', 'MaxValue documentation'),
    new Suggestion('Mbg', 'Mbg detail', 'Mbg documentation'),
    new Suggestion('MinLength', 'MinLength detail', 'MinLength documentation'),
    new Suggestion('MinValue', 'MinValue detail', 'MinValue documentation'),
    new Suggestion('Mod11_10', 'Mod11_10 detail', 'Mod11_10 documentation'),
    new Suggestion('ModificationTimeOf', 'ModificationTimeOf detail', 'ModificationTimeOf documentation'),
    new Suggestion('Module', 'Module detail', 'Module documentation'),
    new Suggestion('Money', 'Money detail', 'Money documentation'),
    new Suggestion('NNRelatedItem', 'NNRelatedItem detail', 'NNRelatedItem documentation'),
    new Suggestion('Oib', 'Oib detail', 'Oib documentation'),
    new Suggestion('OnInitialization', 'OnInitialization detail', 'OnInitialization documentation'),
    new Suggestion('OnSaveUpdate', 'OnSaveUpdate detail', 'OnSaveUpdate documentation'),
    new Suggestion('OnSaveValidate', 'OnSaveValidate detail', 'OnSaveValidate documentation'),
    new Suggestion('Parameter', 'Parameter detail', 'Parameter documentation'),
    new Suggestion('Persisted', 'Persisted detail', 'Persisted documentation'),
    new Suggestion('PessimisticLocking', 'PessimisticLocking detail', 'PessimisticLocking documentation'),
    new Suggestion('PessimisticLockingParent', 'PessimisticLockingParent detail', 'PessimisticLockingParent documentation'),
    new Suggestion('Polymorphic', 'Polymorphic detail', 'Polymorphic documentation'),
    new Suggestion('PrerequisiteAllProperties', 'PrerequisiteAllProperties detail', 'PrerequisiteAllProperties documentation'),
    new Suggestion('PropertyFrom', 'PropertyFrom detail', 'PropertyFrom documentation'),
    new Suggestion('Query', 'Query detail', 'Query documentation'),
    new Suggestion('QueryableExtension', 'QueryableExtension detail', 'QueryableExtension documentation'),
    new Suggestion('Range', 'Range detail', 'Range documentation'),
    new Suggestion('Reference', 'Reference detail', 'Reference documentation'),
    new Suggestion('RegExMatch', 'RegExMatch detail', 'RegExMatch documentation'),
    new Suggestion('Registar', 'Registar detail', 'Registar documentation'),
    new Suggestion('RegisteredImplementation', 'RegisteredImplementation detail', 'RegisteredImplementation documentation'),
    new Suggestion('RelatedItem', 'RelatedItem detail', 'RelatedItem documentation'),
    new Suggestion('ReportData', 'ReportData detail', 'ReportData documentation'),
    new Suggestion('ReportFile', 'ReportFile detail', 'ReportFile documentation'),
    new Suggestion('ReportFileWithParam', 'ReportFileWithParam detail', 'ReportFileWithParam documentation'),
    new Suggestion('Required', 'Required detail', 'Required documentation'),
    new Suggestion('RowPermissions', 'RowPermissions detail', 'RowPermissions documentation'),
    new Suggestion('RowPermissionsRead', 'RowPermissionsRead detail', 'RowPermissionsRead documentation'),
    new Suggestion('RowPermissionsWrite', 'RowPermissionsWrite detail', 'RowPermissionsWrite documentation'),
    new Suggestion('SaveMethod', 'SaveMethod detail', 'SaveMethod documentation'),
    new Suggestion('ShortString', 'ShortString detail', 'ShortString documentation'),
    new Suggestion('Sifrarnik', 'Sifrarnik detail', 'Sifrarnik documentation'),
    new Suggestion('SingleRoot', 'SingleRoot detail', 'SingleRoot documentation'),
    new Suggestion('SmartSearch', 'SmartSearch detail', 'SmartSearch documentation'),
    new Suggestion('Snowflake', 'Snowflake detail', 'Snowflake documentation'),
    new Suggestion('SqlDefault', 'SqlDefault detail', 'SqlDefault documentation'),
    new Suggestion('SqlDependsOn', 'SqlDependsOn detail', 'SqlDependsOn documentation'),
    new Suggestion('SqlDependsOnFunction', 'SqlDependsOnFunction detail', 'SqlDependsOnFunction documentation'),
    new Suggestion('SqlDependsOnSqlObject', 'SqlDependsOnSqlObject detail', 'SqlDependsOnSqlObject documentation'),
    new Suggestion('SqlDependsOnView', 'SqlDependsOnView detail', 'SqlDependsOnView documentation'),
    new Suggestion('SqlFunction', 'SqlFunction detail', 'SqlFunction documentation'),
    new Suggestion('SqlFunctionParameterized', 'SqlFunctionParameterized detail', 'SqlFunctionParameterized documentation'),
    new Suggestion('SqlImplementation', 'SqlImplementation detail', 'SqlImplementation documentation'),
    new Suggestion('SqlIndex', 'SqlIndex detail', 'SqlIndex documentation'),
    new Suggestion('SqlIndexMultiple', 'SqlIndexMultiple detail', 'SqlIndexMultiple documentation'),
    new Suggestion('SqlNotNull', 'SqlNotNull detail', 'SqlNotNull documentation'),
    new Suggestion('SqlObject', 'SqlObject detail', 'SqlObject documentation'),
    new Suggestion('SqlProcedure', 'SqlProcedure detail', 'SqlProcedure documentation'),
    new Suggestion('SqlProcedureParameterized', 'SqlProcedureParameterized detail', 'SqlProcedureParameterized documentation'),
    new Suggestion('SqlQueryable', 'SqlQueryable detail', 'SqlQueryable documentation'),
    new Suggestion('SqlQueryableParameterized', 'SqlQueryableParameterized detail', 'SqlQueryableParameterized documentation'),
    new Suggestion('SqlTrigger', 'SqlTrigger detail', 'SqlTrigger documentation'),
    new Suggestion('SqlView', 'SqlView detail', 'SqlView documentation'),
    new Suggestion('SuppressSynchronization', 'SuppressSynchronization detail', 'SuppressSynchronization documentation'),
    new Suggestion('SystemRequired', 'SystemRequired detail', 'SystemRequired documentation'),
    new Suggestion('Take', 'Take detail', 'Take documentation'),
    new Suggestion('TemplaterReport', 'TemplaterReport detail', 'TemplaterReport documentation'),
    new Suggestion('TemplaterReportWithParam', 'TemplaterReportWithParam detail', 'TemplaterReportWithParam documentation'),
    new Suggestion('TemporalEntity', 'TemporalEntity detail', 'TemporalEntity documentation'),
    new Suggestion('TemporalReferenceEntity', 'TemporalReferenceEntity detail', 'TemporalReferenceEntity documentation'),
    new Suggestion('Unique', 'Unique detail', 'Unique documentation'),
    new Suggestion('UniqueMultiple', 'UniqueMultiple detail', 'UniqueMultiple documentation'),
    new Suggestion('UseExecutionContext', 'UseExecutionContext detail', 'UseExecutionContext documentation'),
    new Suggestion('UserRequired', 'UserRequired detail', 'UserRequired documentation'),
    new Suggestion('Where', 'Where detail', 'Where documentation'),
    new Suggestion('Write', 'Write detail', 'Write documentation')
];

export function isPositionInString(document: vscode.TextDocument, position: vscode.Position): boolean {
	let lineText = document.lineAt(position.line).text;
	let lineTillCurrentPosition = lineText.substr(0, position.character);

	// Count the number of double quotes in the line till current position. Ignore escaped double quotes
	let doubleQuotesCnt = (lineTillCurrentPosition.match(/[^\\]\"/g) || []).length;
	doubleQuotesCnt += lineTillCurrentPosition.startsWith('\"') ? 1 : 0;
	return doubleQuotesCnt % 2 === 1;
}